version: 2
jobs:
  backend:
    docker:
      - image: golang
    working_directory: /go/src/github.com/assetto-corsa-web/acweb
    steps:
      - checkout
      - run: go test .
      - run: go build .
  frontend:
    docker:
      - image: node
    working_directory: /go/src/github.com/assetto-corsa-web/acweb/public
    steps:
      - checkout
      - run: cd /go/src/github.com/assetto-corsa-web/acweb/public && npm i
      - run: cd /go/src/github.com/assetto-corsa-web/acweb/public && npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
      - frontend
