version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/assetto-corsa-web/acweb
    steps:
      - checkout
      - run: go test .
      - run: go build .
