version: 2
jobs:
  backend:
    docker:
      - image: golang
    working_directory: /go/src/github.com/assetto-corsa-web/acweb
    steps:
      - checkout
      - run: go test .
      - run: go build .
  frontend:
    docker:
      - image: node
    working_directory: /go/src/github.com/assetto-corsa-web/acweb/public
    steps:
      - checkout
      - run: cd public && ls
      - run: cd public && npm i
      - run: cd public && npm run build
  docker_image:
    docker:
      - image: docker:18-git
    working_directory: /go/src/github.com/assetto-corsa-web/acweb
    steps:
      - checkout
      - run: docker build -t acweb .
workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
      - frontend
      - docker_image
