version: 2
jobs:
  backend:
    docker:
      - image: golang
    working_directory: /go/src/github.com/assetto-corsa-web/acweb
    steps:
      - checkout
      - run: go test .
      - run: go build .
  frontend:
    docker:
      - image: circleci/node
    working_directory: /go/src/github.com/assetto-corsa-web/acweb/public
    steps:
      - checkout
      - run: npm i
      - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
      - frontend
